apiVersion: v2
name: grafana-stack
description: Umbrella Chart for the "Grafana Stack"

type: application

version: 1.0.0

appVersion: "1.16.0"

dependencies:
  - name: mimir-distributed
    version: 5.4.1
    repository: https://grafana.github.io/helm-charts
  - name: loki
    version: 6.6.2
    repository: https://grafana.github.io/helm-charts
  - name: tempo-distributed
    version: 1.9.0
    repository: https://grafana.github.io/helm-charts
  - name: pyroscope
    version: 1.5.0
    repository: https://grafana.github.io/helm-charts
  - name: alloy
    version: 0.3.2
    repository: https://grafana.github.io/helm-charts
  - name: grafana
    version: 8.8.2
    repository: https://grafana.github.io/helm-charts
